[window]
opacity = 0.92

[font]
size = 15
normal.family = "Pragmasevka Nerd Font"
bold.family = "Pragmasevka Nerd Font"
italic.family = "Pragmasevka Nerd Font"
bold_italic.family = "Pragmasevka Nerd Font"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]
black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[scrolling]
history = 10000

[mouse]
hide_when_typing = true

[cursor]
style = "Beam"
blink_interval = 1000

[selection]
save_to_clipboard = true
